#!/usr/bin/env bash
###########################################################
#  Author     : zhanghao                                  #
###########################################################


#################### Functions ##################################################
shell_folder=$(dirname $(readlink -f "$0"))

CreateConfigFile()
{
  source $shell_folder/PreparationSteps/CreateConfigFile.sh
}

CheckConfigFile()
{
  if  [[ ! -f $1 ]];then
    echo -e "Cannot find the ConfigFile:$ConfigFile !\n"
    exit 1
  else
    echo -e ">>> Find the ConfigFile: $ConfigFile\n"
  fi
}

CreateSampleInfoFile()
{
  source $shell_folder/PreparationSteps/CreateSampleInfoFile.sh
}

CreateWorkDir()
{
  source $1
  source $shell_folder/LoadConfig.sh prepare
  source $shell_folder/PreparationSteps/CreateWorkDir.sh
}

preAlignmentQC()
{
  source $1
  source $shell_folder/LoadConfig.sh 
  source $shell_folder/GeneralSteps/preAlignmentQC.sh
}

Alignment()
{
  source $1
  source $shell_folder/LoadConfig.sh 
  source $shell_folder/GeneralSteps/Alignment.sh
}

postAlignmentQC()
{
  source $1
  source $shell_folder/LoadConfig.sh 
  source $shell_folder/GeneralSteps/postAlignmentQC.sh $shell_folder/GeneralSteps/dupRadar.R
}

Quantification()
{
  source $1
  source $shell_folder/LoadConfig.sh 
  source $shell_folder/ExpressionAnalysis/Quantification.sh $shell_folder/ExpressionAnalysis/Quantification_featurecounts.R $shell_folder/ExpressionAnalysis/Quantification_annotation.R
}

postQuantificationQC()
{
  source $1
  source $shell_folder/LoadConfig.sh 
  source $shell_folder/ExpressionAnalysis/postQuantificationQC.sh $shell_folder/ExpressionAnalysis/postQuantificationQC.R
}

DifferentialExpression()
{
  source $1
  source $shell_folder/LoadConfig.sh 
  source $shell_folder/ExpressionAnalysis/DifferentialExpression.sh $shell_folder/ExpressionAnalysis/DifferentialExpression.R
}

CNVanalysis()
{
  source $1
  source $shell_folder/LoadConfig.sh 
  source $shell_folder/OtherAnalysis/CNV/CNVanalysis.sh $shell_folder/OtherAnalysis/CNV/hmmcopy.R $shell_folder/OtherAnalysis/CNV/SNP2ploidy.R
}

help()
{
cat <<- EOF
#########################################################################################

  Description: A flexible, modularization, and pragmatic workflow to process the NGS data 
               in batches.

  Author: ZhangHao

#########################################################################################

  Usage: 
  
    NGSmodule <MODE> [-c <Config_file>]
  
  MODE options:
    
    > PreparationSteps:
        CreateConfigFile         Create a configuration template file for NGSmodule.
        CreateSampleInfoFile     Create a sample information template file for NGSmodule.
        CreateWorkDir            Create a working directory according to the configuration
                                 file and sample information file.
    
    > GeneralSteps:
        preAlignmentQC           
        Alignment                
        postAlignmentQC          

    > Analysis:
      # Expression:
          Quantification
          postQuantificationQC   
          DifferentialExpression   

      # CNV:
          CNVanalysis
    
  Other options:
    -c, --ConfigFile          Specify the path of ConfigFile. A template configuration 
                              file will be created with <CreateConfigFile> MODE.
    -h, --help                Show this message.
    -v, --version             Show the version of NGSmodule.

#########################################################################################

EOF

}


version_info()
{
cat <<- EOF
################################
    NGSmodule vsersion: 0.1.0   
################################
EOF
}


#################### Parsing the parameters ##################################################
echo  ""
getopt -T &>/dev/null;[ $? -ne 4 ] && { echo "getopt is not enhanced version\n";exit 1; }

parameters=`getopt --options c:hv --longoptions ConfigFile,help,version -n "$0" -- "$@"`
[ $? -ne 0 ] && { echo -e "Try '$0 --help' for more information.\n"; exit 1; }

eval set -- "$parameters" 
while true;do 
  case $1 in
    -c|--ConfigFile) ConfigFile=$2; shift 2;; 
    -h|--help) help; exit 0;; 
    -v|--version) version_info; exit 0;;
    --)
      shift
      if [[ $# == 0 ]];then
        echo -e "Please select a MODE option. Try '$0 --help' for more information.\n"
        exit 1
      elif [[ $1 == "CreateConfigFile" ]];then
        CreateConfigFile $ConfigFile
        exit 0
      elif [[ $1 == "CreateSampleInfoFile" ]];then
        CreateSampleInfoFile
        exit 0
      elif [[ $1 == "CreateWorkDir" ]];then
        { echo "$parameters" | grep -E '\-\-ConfigFile|\-c'; } &>/dev/null
        [ $? -ne 0 ] && { echo -e "ERROR!\nOption -c|--ConfigFile needed in CreateWorkDir MODE!\nTry '$0 --help' for more information.\n"; exit 1; }
        CheckConfigFile $ConfigFile
        CreateWorkDir $ConfigFile
        exit 0      
      elif [[ $1 == "preAlignmentQC" ]];then
        { echo "$parameters" | grep -E '\-\-ConfigFile|\-c'; } &>/dev/null
        [ $? -ne 0 ] && { echo -e "ERROR!\nOption -c|--ConfigFile needed in preAlignmentQC MODE!\nTry '$0 --help' for more information.\n"; exit 1; }
        CheckConfigFile $ConfigFile
        preAlignmentQC $ConfigFile
        exit 0   
      elif [[ $1 == "Alignment" ]];then
        { echo "$parameters" | grep -E '\-\-ConfigFile|\-c'; } &>/dev/null
        [ $? -ne 0 ] && { echo -e "ERROR!\nOption -c|--ConfigFile needed in Alignment MODE!\nTry '$0 --help' for more information.\n"; exit 1; }
        CheckConfigFile $ConfigFile
        Alignment $ConfigFile
        exit 0   
      elif [[ $1 == "postAlignmentQC" ]];then
        { echo "$parameters" | grep -E '\-\-ConfigFile|\-c'; } &>/dev/null
        [ $? -ne 0 ] && { echo -e "ERROR!\nOption -c|--ConfigFile needed in postAlignmentQC MODE!\nTry '$0 --help' for more information.\n"; exit 1; }
        CheckConfigFile $ConfigFile
        postAlignmentQC $ConfigFile
        exit 0   
      elif [[ $1 == "Quantification" ]];then
        { echo "$parameters" | grep -E '\-\-ConfigFile|\-c'; } &>/dev/null
        [ $? -ne 0 ] && { echo -e "ERROR!\nOption -c|--ConfigFile needed in Quantification MODE!\nTry '$0 --help' for more information.\n"; exit 1; }
        CheckConfigFile $ConfigFile
        Quantification $ConfigFile
        exit 0   
      elif [[ $1 == "postQuantificationQC" ]];then
        { echo "$parameters" | grep -E '\-\-ConfigFile|\-c'; } &>/dev/null
        [ $? -ne 0 ] && { echo -e "ERROR!\nOption -c|--ConfigFile needed in postQuantificationQC MODE!\nTry '$0 --help' for more information.\n"; exit 1; }
        CheckConfigFile $ConfigFile
        postQuantificationQC $ConfigFile
        exit 0   
      elif [[ $1 == "DifferentialExpression" ]];then
        { echo "$parameters" | grep -E '\-\-ConfigFile|\-c'; } &>/dev/null
        [ $? -ne 0 ] && { echo -e "ERROR!\nOption -c|--ConfigFile needed in DifferentialExpression MODE!\nTry '$0 --help' for more information.\n"; exit 1; }
        CheckConfigFile $ConfigFile
        DifferentialExpression $ConfigFile
        exit 0   
      elif [[ $1 == "CNVanalysis" ]];then
        { echo "$parameters" | grep -E '\-\-ConfigFile|\-c'; } &>/dev/null
        [ $? -ne 0 ] && { echo -e "ERROR!\nOption -c|--ConfigFile needed in CNVanalysis MODE!\nTry '$0 --help' for more information.\n"; exit 1; }
        CheckConfigFile $ConfigFile
        CNVanalysis $ConfigFile
        exit 0   
      else
        echo -e "Invalid MODE: $1 \nTry '$0 --help' for more information.\n"
      fi
      break ;;
    -*) echo "error: no such option $1.\n"; exit 1;;
    *) echo "error: no such option $1.\n"; exit 1;;
  esac
done
