"""
System Alert database model for monitoring and notifications
"""

import uuid

from sqlalchemy import JSON, Boolean, Column, DateTime, ForeignKey, Index, String, Text
from sqlalchemy.orm import relationship

from app.core.database import Base
from app.core.datetime_utils import utc_now_naive
from app.core.types import UUID


class SystemAlert(Base):
    """
    System alert model for monitoring critical conditions

    Stores alerts generated by system monitoring (disk space,
    memory usage, service health, etc.) that require admin attention.
    """

    __tablename__ = "system_alerts"

    id = Column(UUID(), primary_key=True, default=uuid.uuid4)

    # Alert classification
    type = Column(String(20), nullable=False, index=True)  # error, warning, info
    severity = Column(String(20), nullable=False, index=True)  # critical, high, medium, low

    # Alert content
    title = Column(String(255), nullable=False)
    message = Column(Text, nullable=False)
    source = Column(String(100), nullable=True, index=True)  # system_monitor, security, etc.

    # Resolution tracking
    resolved = Column(Boolean, default=False, nullable=False, index=True)
    resolved_at = Column(DateTime, nullable=True)
    resolved_by = Column(UUID(), ForeignKey("users.id"), nullable=True)
    resolution_notes = Column(Text, nullable=True)

    # Metadata
    alert_metadata = Column(JSON, default=dict)
    occurrence_count = Column(String(10), default="1")  # Track repeated alerts

    # Timestamps
    timestamp = Column(DateTime, default=utc_now_naive, nullable=False, index=True)
    last_seen = Column(DateTime, default=utc_now_naive, nullable=False)

    # Relationships
    resolver = relationship("User", foreign_keys=[resolved_by])

    __table_args__ = (
        Index("ix_alerts_type_severity", "type", "severity"),
        Index("ix_alerts_resolved_timestamp", "resolved", "timestamp"),
    )

    def __repr__(self):
        return f"<SystemAlert {self.severity}/{self.type}: {self.title}>"

    def to_dict(self):
        """Convert alert to dictionary"""
        return {
            "id": str(self.id),
            "type": self.type,
            "severity": self.severity,
            "title": self.title,
            "message": self.message,
            "source": self.source,
            "resolved": self.resolved,
            "resolved_at": self.resolved_at.isoformat() if self.resolved_at else None,
            "resolved_by": str(self.resolved_by) if self.resolved_by else None,
            "resolution_notes": self.resolution_notes,
            "metadata": self.alert_metadata or {},
            "timestamp": self.timestamp.isoformat() if self.timestamp else None,
            "last_seen": self.last_seen.isoformat() if self.last_seen else None,
        }
