/**
 * Common Components Barrel Export
 */
export { PageHeader } from './PageHeader'
export { DataTable } from './DataTable'
export { StatisticCard } from './StatisticCard'
export type { StatisticItem } from './StatisticCard'
export { StatusTag } from './StatusTag'
export type { StatusType } from './StatusTag'
export { EmptyState } from './EmptyState'
export { LoadingSpinner } from './LoadingSpinner'
export { PageTransition } from './PageTransition'
export { SkeletonLoader } from './SkeletonLoader'
export { FloatingActionButton } from './FloatingActionButton'
export { AnimatedCard } from './AnimatedCard'
export { ProgressBar } from './ProgressBar'
export { Tooltip } from './Tooltip'

// Phase 12: New Enhanced Components
export { FilterBar } from './FilterBar'
export type { FilterBarProps, FilterConfig } from './FilterBar'
export { EnhancedEmptyState } from './EnhancedEmptyState'
export type { EnhancedEmptyStateProps } from './EnhancedEmptyState'
export { ErrorBoundary } from './ErrorBoundary'
export { PageSkeleton, TableSkeleton } from './Skeleton'
export type { PageSkeletonProps, TableSkeletonProps } from './Skeleton'
export { FadeIn } from './FadeIn'
export type { FadeInProps } from './FadeIn'
export { StaggeredList } from './StaggeredList'
export type { StaggeredListProps } from './StaggeredList'
